source 'https://cdn.cocoapods.org/'
source 'https://github.com/changjianfeishui/mht-specs'

use_frameworks!

platform :ios, '13.0'

target 'MHTUserModelInterface_Example' do
  pod 'MHTUserModelInterface', :path => '../'

  target 'MHTUserModelInterface_Tests' do
    inherit! :search_paths

    
  end
end
