use_frameworks!

platform :ios, '10.0'

target 'MHTUserModelInterface_Example' do
  pod 'MHTUserModelInterface', :path => '../'

  target 'MHTUserModelInterface_Tests' do
    inherit! :search_paths

    
  end
end
